shell zsh

background_opacity   0.85
background_blur      5

# Police
font_family      Source Code Pro
font_size        14.0
# Espacement
window_padding_width 10

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME